### ISSUE TITLE
NEW UI *BUG* Log Size

### ISSUE THREAD

**Issue by gazoscalvertos** [gazoscalvertos/Hass-Custom-Alarm#36]
When a log size a set the alarm cannot be armed:

Log Details (ERROR)
Fri Aug 03 2018 16:54:41 GMT+0100 (British Summer Time)

Error executing service <ServiceCall alarm_control_panel.alarm_arm_night: code=>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1021, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/alarm_control_panel/__init__.py", line 140, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alarm_control_panel/bwalarm.py", line 807, in alarm_arm_night
    self._update_log('HA', 'Alarm set in Perimeter mode')
  File "/config/custom_components/alarm_control_panel/bwalarm.py", line 980, in _update_log
    if self._log_size != -1 and len(self._config[CONF_LOG]["logs"]) >= self._log_size:
TypeError: '>=' not supported between instances of 'int' and 'str'

**Comment by gazoscalvertos** [comment]
fixed in 1.0.6
